### ISSUE TITLE
CSRF Warning! State not equal in request and response.

### ISSUE THREAD

**Issue by BarryThrill** [weibeu/Flask-Discord#38]
Hello and happy new year!

I have tried for few hours to understand what is going on and yet im coming nowhere!

I did something super simple such as:

```
import os

from flask import Flask, redirect, url_for
from flask_discord import DiscordOAuth2Session, requires_authorization, Unauthorized

app = Flask(__name__)

app.secret_key = b"random bytes representing flask secret key"
os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "true"  # !! Only in development environment.

# Random ids, so its safe!

app.config["DISCORD_CLIENT_ID"] = 7874414230411123123  # Discord client ID.
app.config["DISCORD_CLIENT_SECRET"] = "AwfaefaefafaZqYO6B97TF_sefesfeafesij!"  # Discord client secret.
app.config["DISCORD_REDIRECT_URI"] = "http://127.0.0.1:5000/callback/"  # URL to your callback endpoint.
app.config["DISCORD_BOT_TOKEN"] = "Nzg3NsrgsgsgsgY3MzYw.X9U_-Q._ehaefaagagt7bdf-E"  # Required to access BOT resources.

discord = DiscordOAuth2Session(app)


@app.route("/login/")
def login():
    test = discord.create_session()
    return test


@app.route("/callback/")
def callback():
    discord.callback()
    return redirect(url_for(".me"))


@app.errorhandler(Unauthorized)
def redirect_unauthorized(e):
    return redirect(url_for("login"))


@app.route("/me/")
@requires_authorization
def me():
    user = discord.fetch_user()
    return f"""
    <html>
        <head>
            <title>{user.name}</title>
        </head>
        <body>
            <img src='{user.avatar_url}' />
        </body>
    </html>"""


if __name__ == "__main__":
    app.run()

```

and in discord devs website:

![image](https://user-images.githubusercontent.com/15836342/103378046-635bf500-4ae1-11eb-95a1-00ceaba90a39.png)

Whenever I try to access http://127.0.0.1:5000/login/ -> it asks me to identify myself through discord and then once that is done, it gives me an error with following information:

```
127.0.0.1 - - [30/Dec/2020 20:53:50] "GET /login/ HTTP/1.1" 302 -
[2020-12-30 20:53:52,869] ERROR in app: Exception on /callback/ [GET]
Traceback (most recent call last):
  File "C:\Users\Barry-PC\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Barry-PC\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Barry-PC\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Barry-PC\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Barry-PC\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Barry-PC\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:/Projects/test.py", line 28, in callback
    discord.callback()
  File "C:\Users\Barry-PC\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_discord\client.py", line 157, in callback
    token = self._fetch_token(state)
  File "C:\Users\Barry-PC\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_discord\_http.py", line 93, in _fetch_token
    return discord.fetch_token(
  File "C:\Users\Barry-PC\AppData\Local\Programs\Python\Python38\lib\site-packages\requests_oauthlib\oauth2_session.py", line 239, in fetch_token
    self._client.parse_request_uri_response(
  File "C:\Users\Barry-PC\AppData\Local\Programs\Python\Python38\lib\site-packages\oauthlib\oauth2\rfc6749\clients\web_application.py", line 203, in parse_request_uri_response
    response = parse_authorization_code_response(uri, state=state)
  File "C:\Users\Barry-PC\AppData\Local\Programs\Python\Python38\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 268, in parse_authorization_code_response
    raise MismatchingStateError()
oauthlib.oauth2.rfc6749.errors.MismatchingStateError: (mismatching_state) CSRF Warning! State not equal in request and response.
127.0.0.1 - - [30/Dec/2020 20:53:52] "GET /callback/?code=eavmRSh3BYILRzGYHrr3L4dBy4Tcwu&state=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfX3N0YXRlX3NlY3JldF8iOiI4azd1dk92dUQyc0hKUU5QbU4xNDJpcjY2RjdjdDgifQ.BBGuWC1OH8Sw-CMqprFKnibclJZTQnW6NDlekXfD8rA HTTP/1.1" 500 -

```

im not sure what im doing wrong but I assume it is most likely my end that is wrong but no idea why :D

**Comment by thec0sm0s** [comment]
**RESET YOUR DISCORD APPLICATION SECRETS.**

Thanks for all these info for debugging purpose. The temporary fix to this is downgrade to `Flask-Discord==0.1.63` and `pyjwt==1.7.1`.

**Comment by kilianalias** [comment]
Do you know when this issue will be fixed @weibeu

**Comment by weibeu** [comment]
@kilianalias Try updating your `Flask-Discord` and `pyjwt` to latest version.

**Comment by kilianalias** [comment]
@weibeu I am still having the same error, in the meantime I am using your temporary fix of Flask-Discord==0.1.63 and pyjwt==1.71

**Comment by weibeu** [comment]
Are you sure youre running on latest versions of Flask-Discord and PyJWT? They are: `Flask-Discord==0.1.64` and `PyJWT==2.0.1`

**Comment by weibeu** [comment]
Will close this issue as this thread has been inactive for a while now. **If someone still gets this issue, make sure to update Flask-Discord and pyjwt to latest version**.
If it still doesn't solves your issue, feel free to re-open it.

**Comment by LittleBladed** [comment]
I am on the latest, version, exact same code but same problem

**Comment by weibeu** [comment]
> I am on the latest version, exact same code but same problem

Both flask-discord and pyjwt?

**Comment by LittleBladed** [comment]
> Both flask-discord and pyjwt?
Yup, both latest versions

**Comment by martimartins** [comment]
Happen the same with me.

**Comment by MiranDaniel** [comment]
Issue has still not been resolved

**Comment by weibeu** [comment]
@MiranDaniel did you check with this?


> Will close this issue as this thread has been inactive for a while now. **If someone still gets this issue, make sure to update Flask-Discord and pyjwt to latest version**. If it still doesn't solves your issue, feel free to re-open it.
