### ISSUE TITLE
jwt.exceptions.DecodeError: Not enough segments

### ISSUE THREAD

**Issue by rereyy** [weibeu/Flask-Discord#56]
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/jwt/api_jws.py", line 190, in _load
    signing_input, crypto_segment = jwt.rsplit(b".", 1)
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/container/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/container/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/container/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "./site/fdpy.py", line 63, in callbackk
    discord.callback()
  File "/home/container/.local/lib/python3.8/site-packages/flask_discord/client.py", line 160, in callback
    return jwt.decode(state, current_app.config["SECRET_KEY"], algorithms="HS256")
  File "/home/container/.local/lib/python3.8/site-packages/jwt/api_jwt.py", line 119, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/home/container/.local/lib/python3.8/site-packages/jwt/api_jwt.py", line 90, in decode_complete
    decoded = api_jws.decode_complete(
  File "/home/container/.local/lib/python3.8/site-packages/jwt/api_jws.py", line 149, in decode_complete
    payload, signing_input, header, signature = self._load(jwt)
  File "/home/container/.local/lib/python3.8/site-packages/jwt/api_jws.py", line 193, in _load
    raise DecodeError("Not enough segments") from err
jwt.exceptions.DecodeError: Not enough segments

**Comment by weibeu** [comment]
Can you share how you're setting your flask application SECRET_KEY.

**Comment by rereyy** [comment]
`app.secret_key = 'secret'`

**Comment by weibeu** [comment]
Can you ensure these two things:
- You're not using mixed callback URLs. As like 127.0.0.1 and localhost. https://github.com/weibeu/Flask-Discord/issues/26#issuecomment-692439451
- Your pyjwt and flask-discord version is latest.

**Comment by weibeu** [comment]
Closing this due to inactivity. Reopen if issue is still persisting.
